### ISSUE TITLE
Buffer not filtering

### ISSUE THREAD

**Issue by WDonner** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#22]
HI Rich. The buffer filter does not appear to work properly in the NBN Atlas Tool for QGIS 3.0.3. It creates a buffer as normal but there is no filtering. It still works fine for 2.18. Can you confirm if the procedure has changed or is this an actual 'bug'? Cheers. Wayne.

**Comment by burkmarr** [comment]
Hi Wayne. I think in version 2.x the circle buffer was selected by default by in version 3.x it is not. So you also have to make sure that you select the object (i.e. the circle buffer) *and* it has to be the active layer in the layers panel. I have it working on QGIS 3.0.1 when I make sure that those two conditions are met. Before you hit the button to create your WMS map (or download records) make sure that the 'Polygon' checkbox in the 'Specified filters' is ticked. (You can't tick it yourself - you have to set the active layer and select the polygon to tick it.)

**Comment by burkmarr** [comment]
Hello Wayne. It looks like this is still a problem (see #29) so I'm reopening the issue.

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polygon filter for NBN queries not always working as expected.](https://trello.com/c/XmcIPS4h/37-polygon-filter-for-nbn-queries-not-always-working-as-expected)

**Comment by WDonner** [comment]
Hi Rich.
Thanks for letting me know, it's appreciated. Look forward to the update.
Wayne

**Comment by burkmarr** [comment]
Added for upcoming release 3.2.
