### ISSUE TITLE
POSSIBILITY TO SELECT RECORDS FROM MULTIPLE LAYERS BY RADIUS

### ISSUE THREAD

**Issue by bwmoths** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#36]

**Comment by bwmoths** [comment]
Is it possible to select biological records from several layers in qgis ? if not is it possible to create such a feature within the TomBio environment

**Comment by burkmarr** [comment]
It depends what you mean exactly. In QIGS you can select features from as many layers as you like but these are treated as separate selections and not as a single collection. You couldn't, for example, select features from two layers and then export these into a single new layer. What is it that you are aiming to do?

**Comment by bwmoths** [comment]
Hi, sorry to have been a bit vague ! Often for things like planning applications there is a need to extract biological records around a given location, usualy 2km or perhaps 5km radius. If one has a number of datasets such as say- mammals, ornithology, botany etc., expressed as layers in a project it would be useful to be able to define a circular area around a point that would allow for the extraction of the biological records from all layers and export that data to a file/spreadsheet perhaps ? Hope this helps.

**Comment by bwmoths** [comment]
Hi again, on reflection it is probably impracticle to select from multiple layers with perhaps differing data formats but, it would be useful to extract from one selected layer the records within the circular area.

**Comment by burkmarr** [comment]
You can do that with QGIS's 'select by location' tool (from the Vector > Research Tools menu or the Processing toolbox) - it's a really useful tool.

**Comment by bwmoths** [comment]
Thanks for the pointer ! I will see if I can make it work !!!

**Comment by bwmoths** [comment]
Thanks again Rich ! That seems to do the job !!

**Comment by burkmarr** [comment]
No worries.
