### ISSUE TITLE
User Defined Grid

### ISSUE THREAD

**Issue by BurwellHistory** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#43]
In previous versions, the grid size/Grid Ref precision picklist had the option to set a user-defined grid size. That is missing from the picklist options yet the Grid Size field is still present but will not allow entry. Will this be re-instated or do I need to keep setting up user-defined grids in QGIS 2.18? This was a most useful feature, which I sincerely hope will be re-introduced.
Thank you

**Comment by burkmarr** [comment]
It's still there, but UI has changed. Now you select 'other' from radio buttons (British, Irish, Other) and then you can set a grid size of your choice which will be in the map units of whatever the current map view (project) CRS is.
