### ISSUE TITLE
Can't see bottom of Biological records panel when docked

### ISSUE THREAD

**Issue by MAPlanGo** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#45]
I've seen this issue on a lot a machines when people come on my courses. Seems to be a that users often can't see the bottom bit of the Biological records toolbar when it is docked. This is a big issue as you need that bit to generate and remove the layers and exports. Work around is to have free floating panel but this quickly becomes a pain to use!

**Comment by burkmarr** [comment]
I think I've seen this before too (though not often). The controls on the panel do take up a lot of room and perhaps do not always fit in the vertical space available. I think that this could be mitigated by putting the drop-down field selection lists in one of the QT container widgets that can be shown or 'hidden' (can't remember what it's called).

**Comment by John-Handley** [comment]
Hi Rich,

I have this same problem although just undocking it enables me to use the buttons at the bottom.
I'm using the latest stable version on QGIS.

Best wishes, John

**Comment by burkmarr** [comment]
Hi John - I implemented the fix with the drop-down field selection lists some time ago. So with the latest version you should be able to just hide the controls to see the full dialog.

With all sections expanded:

![image](https://user-images.githubusercontent.com/9275178/98522253-5ef72680-226c-11eb-80ff-94a299ecd6f3.png)

With all sections closed:

![image](https://user-images.githubusercontent.com/9275178/98522330-76361400-226c-11eb-8f7f-7024e25d423e.png)

**Comment by John-Handley** [comment]
Thanks Rich,

I hadn't thought to unexpand the sections, that's absolutely fine.

It is such a great tool, one I use almost every time I open up QGIS. Is
there a way to donate to say a direct thank you for it's construction and
maintenance please?

Best wishes, John

--

John Handley MSc



[image: CH Logo & address]

**Comment by burkmarr** [comment]
That's very good of you John. Since FSC sponsored the initial development (through the Tomorrow's Biodiversity project) and continue to support the plugin, you could consider making a donation to them. I'd advise contacting Keiron Brown through the BioLinks project to talk about it.
