### ISSUE TITLE
Updating map when csv changes

### ISSUE THREAD

**Issue by kinglouis-123** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#46]
Not sure if I should be here or in the forum.... I'm trying to work out how I can update the map layer automatically when a .csv is changed. I can do this directly in QGIS using the Watch File checkbox when creating a layer from the .csv. But as FSC tools neatly simplifies this stage I can't seem to do it with maps I've created with the FSC tool. I can't find a way to Watch File after the layer is created, only at the create layer stage. I'm quite new to this so might be missing something obvious. Thanks.

**Comment by burkmarr** [comment]
The forum is the better place for questions like this. I've posted your question along with my answer there: https://forum.fscbiodiversity.uk/t/watch-file-capability-for-biological-records-tool/72
