### ISSUE TITLE
Composer image not creating image files in output folder

### ISSUE THREAD

**Issue by xaviermestdagh** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#67]
Hi,
I wanted to update layout of maps I produced with success some months ago with ToMBio plugin but now I don't see image files produced in the output directory when using composer image in output options. With Composer pdf, pdf files are produced but compleatly empty (without the map). In the layout window of QGIS (the composer), I see the distribution maps updated with symbols of the several species, but the files are not produced... 
Sorry I didn't find other issue related to that...
I am using QGIS 3.10.12 and just updated to TomBio 3.4.2 to try to fix this bug... 
Many thanks in advance for your help!

**Comment by burkmarr** [comment]
Hello I've just verified that both the 'composer pdf' and 'composer image' output options work with version 3.4.2 of the plugin and versions 3.10.0 and 3.28.7 (current long-term release). I've also used 3.4.2 with many other versions of QGIS without problem. It's likely that you have missed a step in your workflow. If you create a bullet list showing your steps, I may be able to see what's wrong.

**Comment by xaviermestdagh** [comment]
Hi, sorry I made it work finally by updating to QGIS 3.32 and using a new layout for the composer image (not duplicating it from other project). Nothing to say on TomBio plugin, still very useful. 
Thanks!
